<a href="https://colab.research.google.com/github/dulcioris/dulcioris/blob/main/Pr2_AMN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Problema 1

## a) Considerando lo anterior, determina cual de los elementos del conjunto A puede representarse de manera exacta en una computadora.

In [1]:
for n in range(1, 10):
    x = n / 10
    num, denom = x.as_integer_ratio()
    print(f"{x} -> {num}/{denom} (Exacto: {denom & (denom - 1) == 0})")

0.1 -> 3602879701896397/36028797018963968 (Exacto: True)
0.2 -> 3602879701896397/18014398509481984 (Exacto: True)
0.3 -> 5404319552844595/18014398509481984 (Exacto: True)
0.4 -> 3602879701896397/9007199254740992 (Exacto: True)
0.5 -> 1/2 (Exacto: True)
0.6 -> 5404319552844595/9007199254740992 (Exacto: True)
0.7 -> 3152519739159347/4503599627370496 (Exacto: True)
0.8 -> 3602879701896397/4503599627370496 (Exacto: True)
0.9 -> 8106479329266893/9007199254740992 (Exacto: True)


In [3]:
# Lista de elementos de A
A = [n / 10 for n in range(1, 10)]

# Función para verificar representación exacta
def es_exacto(numero):
    numerador, denominador = numero.as_integer_ratio()
    # Verifica si el denominador es una potencia de 2
    return (denominador & (denominador - 1)) == 0

# Verificar cada elemento de A
resultados = [(n, es_exacto(n)) for n in A]

# Mostrar resultados
for valor, exacto in resultados:
    print(f"{valor}: {'Exacto' if exacto else 'No exacto'}")

0.1: Exacto
0.2: Exacto
0.3: Exacto
0.4: Exacto
0.5: Exacto
0.6: Exacto
0.7: Exacto
0.8: Exacto
0.9: Exacto


##b) Determina el valor mínimo de  n  para el cual el número mostrado en Python usando la función format() es distinto del valor real de los elementos de  A  que no pueden representarse de forma exacta.

In [12]:
# Lista de elementos de A
A = [n / 10 for n in range(1, 10)]

# Verificar usando format() si el valor mostrado es igual al real
for n, valor in enumerate(A, start=1):
    formateado = format(valor, '.17f')  # Usando 17 decimales de precisión para 64 bits
    if formateado != f'{valor:.17f}':   # Comparando las cadenas formateadas
        print(f"El valor mínimo de n es {n} para el cual format() difiere del valor real.")
        break
else:
    print("Todos los valores coinciden.")

Todos los valores coinciden.


##c) Utiliza tu resultado del inciso anterior para determinar el error absoluto y relativo para cada uno de los elementos de  A .

In [13]:
for n in range(1, 10):
    x = n / 10
    formatted_x = float(format(x, '.17f'))
    error_absoluto = abs(x - formatted_x)
    error_relativo = error_absoluto / abs(x) if x != 0 else 0
    print(f"{x} -> Error Absoluto: {error_absoluto}, Error Relativo: {error_relativo}")

0.1 -> Error Absoluto: 0.0, Error Relativo: 0.0
0.2 -> Error Absoluto: 0.0, Error Relativo: 0.0
0.3 -> Error Absoluto: 0.0, Error Relativo: 0.0
0.4 -> Error Absoluto: 0.0, Error Relativo: 0.0
0.5 -> Error Absoluto: 0.0, Error Relativo: 0.0
0.6 -> Error Absoluto: 0.0, Error Relativo: 0.0
0.7 -> Error Absoluto: 0.0, Error Relativo: 0.0
0.8 -> Error Absoluto: 0.0, Error Relativo: 0.0
0.9 -> Error Absoluto: 0.0, Error Relativo: 0.0


#Problema 2

##a) Escribe una función en Python que calcule el promedio y la varianza de un arreglo.

In [14]:
def calcular_promedio_varianza(arr):
    suma = 0
    suma_cuadrados = 0
    n = len(arr)

    # Itera sobre los elementos del arreglo
    for x in arr:
        suma += x
        suma_cuadrados += x ** 2

    # Calcula el promedio
    promedio = suma / n

    # Calcula la varianza
    varianza = (suma_cuadrados / n) - (promedio ** 2)

    print(f"Promedio: {promedio}")
    print(f"Varianza: {varianza}")
    return promedio, varianza

# Crear el arreglo aleatorio usando numpy
import numpy as np

arr = np.random.uniform(10000000, 10000000.06, 100000)

# Llamar a la función con el arreglo generado
promedio, varianza = calcular_promedio_varianza(arr)

Promedio: 10000000.02997933
Varianza: -0.78125


Comparación con numpy

In [15]:
# Calcula el promedio y la varianza usando numpy
promedio_numpy = np.mean(arr)
varianza_numpy = np.var(arr)

print(f"Promedio con NumPy: {promedio_numpy}")
print(f"Varianza con NumPy: {varianza_numpy}")

# Comparación de resultados
diferencia_promedio = abs(promedio - promedio_numpy)
diferencia_varianza = abs(varianza - varianza_numpy)

print(f"Diferencia en Promedio: {diferencia_promedio}")
print(f"Diferencia en Varianza: {diferencia_varianza}")

Promedio con NumPy: 10000000.02997927
Varianza con NumPy: 0.0003002145998956093
Diferencia en Promedio: 5.960464477539063e-08
Diferencia en Varianza: 0.7815502145998956


##b) Cálculo de módulos y explicación del resultado

In [16]:
# Cálculos solicitados
mod_1 = 13.716 % 4.572
mod_2 = 16.6461 % 5.5487

print(f"13.716 % 4.572 = {mod_1}")
print(f"16.6461 % 5.5487 = {mod_2}")

13.716 % 4.572 = 4.571999999999999
16.6461 % 5.5487 = 0.0


Aunque $3 \times 4.572 = 13.716$ y $3 \times 5.5487 = 16.6461$, al calcular los módulos obtuve resultados mayores a 1 por las limitaciones de los números de punto flotante. Esto ocurre porque las operaciones de multiplicación y división no son exactas para todos los números en la aritmética de punto flotante.

Otro ejemplo de un par de números podría ser  $x = 0.1$ y  $y = 0.3$. En este caso, aunque  $y = 3 \times x$ , la operación $y \% x$  no da exactamente 0 debido a las imprecisiones:

In [17]:
x = 0.1
y = 0.3
print(f"0.3 % 0.1 = {y % x}")  # Este no será exactamente 0

0.3 % 0.1 = 0.09999999999999998


#Problema 3

##a) Proponer una forma de escribir la comparación para que el resultado sea True

In [18]:
import math

# Comparación usando math.isclose()
resultado = math.isclose(0.1 + 0.1 + 0.1, 0.3)
print(resultado)  # Esto imprimirá True

True


In [19]:
# Definir una pequeña tolerancia
epsilon = 1e-9

# Comparación manual con margen de error
resultado = abs((0.1 + 0.1 + 0.1) - 0.3) < epsilon
print(resultado)  # Esto también imprimirá True

True


##b) Considera el siguiente código

El bucle while a != 0: nunca termina porque a nunca será exactamente igual a 0 debido a las imprecisiones de punto flotante en las operaciones de resta sucesiva con a -= 0.001. La variable a se acercará infinitamente a cero, pero no lo alcanzará exactamente, lo cual hace que la condición a != 0 siempre sea verdadera.

In [22]:
a = 1000
while a > 0:  # Cambiar la comparación
    x = a * n
    a -= 0.001